spring.application.name=quizapp
spring.datasource.driver-class-name=org.postgresql.Driver
spring.datasource.url=jdbc:postgresql://localhost:5432/questiondb
spring.datasource.username=postgres
spring.datasource.password=rishika
spring.jpa.properties.hibernate.ddl-auto=update
#spring.jpa.properties.hibernate.dialect= org.hibernate.dialect.PostgreSQLDialect
# Ensures camelCase in Java matches snake_case in Postgres
spring.jpa.hibernate.naming.physical-strategy=org.hibernate.boot.model.naming.CamelCaseToUnderscoresNamingStrategy

# Useful for debugging if the data still doesn't show
spring.jpa.show-sql=true